export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDERS_LIST_CLIENT_REQUEST = 'ORDERS_LIST_CLIENT_REQUEST';
export const ORDERS_LIST_CLIENT_SUCCESS = 'ORDERS_LIST_CLIENT_SUCCESS';
export const ORDERS_LIST_CLIENT_FAIL = 'ORDERS_LIST_CLIENT_FAIL';
export const ORDERS_LIST_CLIENT_RESET = 'ORDERS_LIST_CLIENT_RESET';
